# Generated by Django 5.0.2 on 2024-02-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
